---
- name: Configure Deployment Server functionality
  hosts: my_ds
  become: true 
  vars_files:
    - /opt/deployment-apps/splunk_creds.yml
  tasks:
    - name: Copy local deployment_apps contents to /etc/deployment-apps on Deployment Server 
      synchronize:
        src: /opt/deployment-apps/apps/
        dest: /opt/splunk/etc/deployment-apps/
    - name: Copy local serverclass.conf contents to /etc/system/local on Deployment Server
      synchronize:
        src: /opt/deployment-apps/serverclass.conf
        dest: /opt/splunk/etc/system/local/
    - name: Fix permissions
      command:
        cmd: chown -R splunk:splunk /opt/splunk      
    - name: Reload Deployment Server
      command:
        cmd: /opt/splunk/bin/splunk reload deploy-server -auth "{{ splunk_username }}":"{{ splunk_password }}"
